CREATE TABLE Product (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Category VARCHAR(50),
    Price DECIMAL(10, 2),
    StockQuantity INT
);


INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (1, 'QuantumCore Processor', 'Electronics', 799.99, 88);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (2, 'Celestial Silk Scarf', 'Apparel', 89.50, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (3, 'Organic Ambrosia Apple Juice', 'Groceries', 5.25, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (4, 'Everest Hiking Backpack', 'Sports & Outdoors', 149.95, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (5, 'The Alchemist''s Secret', 'Books', 14.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (6, 'Artisan Sourdough Bread', 'Groceries', 6.50, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (7, 'HydroLuxe Water Bottle', 'Home & Kitchen', 24.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (8, 'Zenith Noise-Cancelling Headphones', 'Electronics', 249.00, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (9, 'Nomad Leather Wallet', 'Accessories', 59.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (10, 'Crimson Peak Winter Jacket', 'Apparel', 299.99, 75);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (11, 'Galactic Odyssey Puzzle (1000pc)', 'Toys & Games', 19.95, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (12, 'Aromatherapy Essential Oil Diffuser', 'Health & Beauty', 39.99, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (13, 'Gourmet Dark Chocolate Bar', 'Groceries', 4.75, 600);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (14, 'Pro-Grip Yoga Mat', 'Sports & Outdoors', 45.00, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (15, 'Chronicles of Eldoria', 'Books', 22.50, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (16, 'ErgoComfort Office Chair', 'Furniture', 349.99, 60);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (17, 'Titanium Chef''s Knife', 'Home & Kitchen', 89.99, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (18, 'Nova Smartwatch Series 5', 'Electronics', 399.00, 95);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (19, 'Cashmere Throw Blanket', 'Home & Kitchen', 129.99, 85);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (20, 'Vintage Denim Jeans', 'Apparel', 79.95, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (21, 'Starlight Projector Lamp', 'Home & Kitchen', 29.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (22, 'Herbal Infusion Tea Set', 'Groceries', 18.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (23, 'Shadows of the Forgotten', 'Books', 12.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (24, 'Compact Travel Umbrella', 'Accessories', 15.99, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (25, 'Professional Sketchbook', 'Arts & Crafts', 17.50, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (26, 'SolarFlare Portable Charger', 'Electronics', 49.99, 170);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (27, 'Bamboo Cutting Board Set', 'Home & Kitchen', 34.50, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (28, 'Velocity Running Shoes', 'Sports & Outdoors', 119.99, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (29, 'Echoes of Tomorrow', 'Books', 18.75, 155);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (30, 'Silk Sleep Mask', 'Health & Beauty', 22.00, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (31, 'Stainless Steel French Press', 'Home & Kitchen', 42.95, 165);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (32, 'Organic Quinoa', 'Groceries', 8.99, 550);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (33, 'Waterproof Dry Bag', 'Sports & Outdoors', 25.99, 195);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (34, 'The Glass Castle', 'Books', 9.99, 480);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (35, 'LED Desk Lamp with Wireless Charging', 'Office Supplies', 55.00, 115);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (36, 'Terraforming Mars Board Game', 'Toys & Games', 69.95, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (37, 'Natural Bristle Dry Brush', 'Health & Beauty', 12.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (38, 'Ultra-Light Camping Tent', 'Sports & Outdoors', 199.50, 70);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (39, 'A Brief History of Time', 'Books', 15.25, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (40, 'Smart WiFi Light Bulb', 'Electronics', 14.99, 650);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (41, 'Cold Brew Coffee Maker', 'Home & Kitchen', 38.00, 145);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (42, 'Merino Wool Hiking Socks', 'Apparel', 21.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (43, 'The Midnight Library', 'Books', 13.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (44, 'Resistance Band Set', 'Sports & Outdoors', 29.99, 410);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (45, 'Ceramic Non-Stick Frying Pan', 'Home & Kitchen', 49.95, 185);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (46, 'Portable Bluetooth Speaker', 'Electronics', 65.00, 215);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (47, 'The Silent Patient', 'Books', 11.80, 430);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (48, 'Organic Coconut Oil', 'Groceries', 12.99, 490);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (49, 'Memory Foam Travel Pillow', 'Accessories', 32.50, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (50, 'Watercolor Paint Set', 'Arts & Crafts', 28.99, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (51, 'Apex Gaming Mouse', 'Electronics', 79.99, 135);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (52, 'Linen Button-Down Shirt', 'Apparel', 65.00, 205);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (53, 'Where the Crawdads Sing', 'Books', 10.50, 510);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (54, 'Insulated Food Jar', 'Home & Kitchen', 27.95, 275);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (55, 'Adjustable Dumbbell Set', 'Sports & Outdoors', 399.99, 55);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (56, 'Jade Facial Roller', 'Health & Beauty', 19.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (57, 'The Vanishing Half', 'Books', 16.20, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (58, 'Electric Gooseneck Kettle', 'Home & Kitchen', 59.99, 125);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (59, 'Polarized Aviator Sunglasses', 'Accessories', 149.00, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (60, 'Sapiens: A Brief History of Humankind', 'Books', 19.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (61, 'Mechanical Gaming Keyboard', 'Electronics', 129.95, 98);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (62, 'Organic Matcha Green Tea Powder', 'Groceries', 24.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (63, 'The Four Winds', 'Books', 14.75, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (64, 'Collapsible Silicone Food Containers', 'Home & Kitchen', 22.99, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (65, 'Foam Roller for Muscle Recovery', 'Sports & Outdoors', 18.50, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (66, 'Atomic Habits', 'Books', 17.00, 550);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (67, 'Vitamin C Serum', 'Health & Beauty', 28.00, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (68, '4K Ultra HD Webcam', 'Electronics', 99.99, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (69, 'The Hill We Climb', 'Books', 9.95, 600);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (70, 'Cast Iron Skillet', 'Home & Kitchen', 35.00, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (71, 'Dune', 'Books', 11.25, 470);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (72, 'Trekking Poles', 'Sports & Outdoors', 55.99, 175);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (73, 'Classic Canvas Tote Bag', 'Accessories', 29.95, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (74, 'Educated: A Memoir', 'Books', 13.99, 490);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (75, 'Digital Kitchen Scale', 'Home & Kitchen', 19.99, 520);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (76, 'Wireless Charging Pad', 'Electronics', 25.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (77, 'Project Hail Mary', 'Books', 20.50, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (78, 'Bamboo Bath Caddy Tray', 'Home & Kitchen', 45.99, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (79, 'The Song of Achilles', 'Books', 12.80, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (80, 'Microfiber Cleaning Cloths (12-Pack)', 'Home & Kitchen', 14.99, 700);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (81, 'Circe', 'Books', 14.25, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (82, 'Smart Reusable Notebook', 'Office Supplies', 34.97, 225);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (83, 'Kombucha Starter Kit', 'Groceries', 45.00, 105);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (84, 'Becoming', 'Books', 18.99, 410);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (85, 'Portable Hammock with Straps', 'Sports & Outdoors', 39.95, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (86, 'Glass Meal Prep Containers', 'Home & Kitchen', 39.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (87, 'The Guest List', 'Books', 11.50, 440);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (88, 'Electric Toothbrush with 5 Modes', 'Health & Beauty', 49.99, 195);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (89, 'Anxious People', 'Books', 15.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (90, 'Mesh WiFi System', 'Electronics', 299.99, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (91, 'The Seven Husbands of Evelyn Hugo', 'Books', 13.75, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (92, 'Silicone Baking Mat Set', 'Home & Kitchen', 16.95, 480);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (93, 'Pickleball Paddle Set', 'Sports & Outdoors', 75.00, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (94, 'Klara and the Sun', 'Books', 19.80, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (95, 'Fountain Pen with Ink Bottle', 'Office Supplies', 42.00, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (96, 'Himalayan Salt Lamp', 'Home & Kitchen', 29.98, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (97, 'The Invisible Life of Addie LaRue', 'Books', 17.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (98, 'Magnetic Knife Strip', 'Home & Kitchen', 21.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (99, 'Weighted Blanket', 'Home & Kitchen', 89.99, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (100, 'Codenames Board Game', 'Toys & Games', 19.95, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (101, 'Nebula Gaming Chair', 'Furniture', 289.50, 45);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (102, 'Artisan Coffee Beans - Ethiopian Yirgacheffe', 'Groceries', 19.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (103, 'Echoes of the Past - Vinyl Record', 'Music', 29.95, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (104, 'Terra Botanica Indoor Plant Pot', 'Garden', 25.50, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (105, 'Stealth Drone X-15', 'Electronics', 499.00, 30);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (106, 'The Art of Fermentation', 'Books', 35.00, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (107, 'Performance Polo Shirt', 'Apparel', 49.95, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (108, 'Sunrise Alarm Clock', 'Home & Kitchen', 45.99, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (109, 'Professional Watercolor Paper Block', 'Arts & Crafts', 22.75, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (110, 'Titan Fitness Tracker', 'Sports & Outdoors', 99.99, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (111, 'Luxury Bath Bomb Set', 'Health & Beauty', 32.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (112, 'The Martian', 'Books', 10.99, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (113, 'Portable Espresso Maker', 'Home & Kitchen', 64.99, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (114, 'Carbon Fiber Trekking Poles', 'Sports & Outdoors', 89.95, 95);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (115, 'Minimalist Leather Backpack', 'Accessories', 189.00, 70);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (116, 'The Subtle Art of Not Giving a F*ck', 'Books', 15.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (117, 'Smart Meat Thermometer', 'Home & Kitchen', 99.00, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (118, 'Organic Spirulina Powder', 'Health & Beauty', 18.75, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (119, 'Wingspan Board Game', 'Toys & Games', 55.00, 100);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (120, 'Thinking, Fast and Slow', 'Books', 16.50, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (121, 'Ultra-Thin Laptop Sleeve', 'Electronics', 24.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (122, 'Hand-Poured Soy Candle - Lavender', 'Home & Kitchen', 22.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (123, 'The Power of Now', 'Books', 12.50, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (124, 'Gore-Tex Rain Jacket', 'Apparel', 249.99, 85);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (125, 'Acrylic Paint Set (24 Colors)', 'Arts & Crafts', 32.99, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (126, '1984', 'Books', 8.99, 650);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (127, 'Electric Wine Opener', 'Home & Kitchen', 29.95, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (128, 'Headlamp for Camping and Hiking', 'Sports & Outdoors', 19.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (129, 'To Kill a Mockingbird', 'Books', 9.50, 580);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (130, 'Portable Garment Steamer', 'Home & Kitchen', 36.99, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (131, 'The Great Gatsby', 'Books', 7.99, 700);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (132, 'Digital Body Weight Scale', 'Health & Beauty', 28.99, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (133, 'Pride and Prejudice', 'Books', 8.25, 620);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (134, 'Insulated Tumbler with Lid and Straw', 'Home & Kitchen', 21.95, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (135, 'The Catcher in the Rye', 'Books', 9.99, 530);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (136, 'USB-C Hub Multiport Adapter', 'Electronics', 45.50, 170);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (137, 'The Hobbit', 'Books', 11.99, 480);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (138, 'Electric Hand Mixer', 'Home & Kitchen', 32.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (139, 'Fahrenheit 451', 'Books', 10.25, 510);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (140, 'Reusable Silicone Storage Bags', 'Home & Kitchen', 18.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (141, 'The Lord of the Rings', 'Books', 25.00, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (142, 'Air Purifier for Home', 'Home & Kitchen', 129.99, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (143, 'Jane Eyre', 'Books', 8.50, 590);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (144, 'Sleep Headphones & Eye Mask', 'Health & Beauty', 23.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (145, 'Animal Farm', 'Books', 7.50, 680);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (146, 'Sous Vide Precision Cooker', 'Home & Kitchen', 149.00, 75);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (147, 'The Diary of a Young Girl', 'Books', 9.75, 540);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (148, 'Ergonomic Vertical Mouse', 'Electronics', 39.99, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (149, 'Brave New World', 'Books', 10.50, 520);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (150, 'Robot Vacuum Cleaner', 'Home & Kitchen', 279.99, 65);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (151, 'Cosmos', 'Books', 22.00, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (152, 'Organic Turmeric Powder', 'Groceries', 7.99, 430);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (153, 'The Hitchhiker''s Guide to the Galaxy', 'Books', 9.99, 460);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (154, 'Standing Desk Converter', 'Office Supplies', 179.95, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (155, 'The Stand', 'Books', 18.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (156, 'Water Flosser Professional', 'Health & Beauty', 59.95, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (157, 'The Shining', 'Books', 12.99, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (158, 'Document Scanner', 'Electronics', 299.00, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (159, 'It', 'Books', 15.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (160, 'Espresso Machine', 'Home & Kitchen', 499.99, 40);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (161, 'The Road', 'Books', 11.50, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (162, 'Noise-Isolating Earplugs', 'Health & Beauty', 15.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (163, 'Blood Meridian', 'Books', 14.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (164, 'Portable Projector', 'Electronics', 199.99, 70);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (165, 'Moby Dick', 'Books', 10.75, 490);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (166, 'Blender for Shakes and Smoothies', 'Home & Kitchen', 89.95, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (167, 'War and Peace', 'Books', 19.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (168, 'UV Light Sanitizer Wand', 'Health & Beauty', 34.99, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (169, 'The Count of Monte Cristo', 'Books', 16.75, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (170, '3D Printer', 'Electronics', 349.00, 55);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (171, 'Anna Karenina', 'Books', 14.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (172, 'Digital Photo Frame', 'Electronics', 79.99, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (173, 'The Brothers Karamazov', 'Books', 17.25, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (174, 'Air Fryer Toaster Oven Combo', 'Home & Kitchen', 159.99, 85);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (175, 'Crime and Punishment', 'Books', 13.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (176, 'Shiatsu Back and Neck Massager', 'Health & Beauty', 55.99, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (177, 'Wuthering Heights', 'Books', 9.25, 560);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (178, 'Record Player with Bluetooth', 'Electronics', 129.95, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (179, 'Frankenstein', 'Books', 8.99, 600);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (180, 'Immersion Blender', 'Home & Kitchen', 42.50, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (181, 'Dracula', 'Books', 9.50, 570);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (182, 'Electric Can Opener', 'Home & Kitchen', 24.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (183, 'The Picture of Dorian Gray', 'Books', 10.99, 480);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (184, 'Fabric Shaver and Lint Remover', 'Home & Kitchen', 16.99, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (185, 'A Tale of Two Cities', 'Books', 8.75, 610);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (186, 'Paper Shredder', 'Office Supplies', 54.99, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (187, 'Les Misérables', 'Books', 19.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (188, 'Label Maker Machine', 'Office Supplies', 38.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (189, 'The Odyssey', 'Books', 11.75, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (190, 'Laminator Machine', 'Office Supplies', 49.99, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (191, 'The Iliad', 'Books', 11.75, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (192, 'Foot Spa Massager', 'Health & Beauty', 69.99, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (193, 'Don Quixote', 'Books', 18.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (194, 'White Noise Machine', 'Health & Beauty', 29.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (195, 'Paradise Lost', 'Books', 12.25, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (196, 'Car Phone Mount', 'Electronics', 17.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (197, 'The Divine Comedy', 'Books', 15.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (198, 'Portable Tire Inflator', 'Automotive', 49.99, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (199, 'The Canterbury Tales', 'Books', 13.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (200, 'Dash Cam', 'Electronics', 89.99, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (201, 'Zen Garden Kit', 'Home & Kitchen', 24.95, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (202, 'Premium Olive Oil', 'Groceries', 22.50, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (203, 'The Art of War', 'Books', 7.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (204, 'Bonsai Tree Starter Kit', 'Garden', 34.99, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (205, 'Solar Powered Garden Lights', 'Garden', 45.99, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (206, 'Meditations', 'Books', 9.95, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (207, 'Bird Feeder', 'Garden', 29.99, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (208, 'The Republic', 'Books', 11.50, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (209, 'Gardening Tool Set', 'Garden', 39.95, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (210, 'The Prince', 'Books', 8.50, 480);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (211, 'Herb Garden Starter Kit', 'Garden', 26.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (212, 'Leviathan', 'Books', 14.25, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (213, 'Compost Bin', 'Garden', 79.99, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (214, 'On the Origin of Species', 'Books', 16.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (215, 'Rain Barrel', 'Garden', 129.95, 60);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (216, 'Walden', 'Books', 10.99, 410);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (217, 'Kettlebell Set', 'Sports & Outdoors', 89.99, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (218, 'Civil Disobedience', 'Books', 6.99, 600);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (219, 'Pull Up Bar for Doorway', 'Sports & Outdoors', 35.50, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (220, 'The Wealth of Nations', 'Books', 21.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (221, 'Jump Rope', 'Sports & Outdoors', 14.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (222, 'The Communist Manifesto', 'Books', 5.99, 700);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (223, 'Ab Roller Wheel', 'Sports & Outdoors', 22.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (224, 'The Interpretation of Dreams', 'Books', 15.75, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (225, 'Balance Board', 'Sports & Outdoors', 49.95, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (226, 'Beyond Good and Evil', 'Books', 12.99, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (227, 'Boxing Gloves', 'Sports & Outdoors', 45.00, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (228, 'Thus Spoke Zarathustra', 'Books', 13.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (229, 'Punching Bag', 'Sports & Outdoors', 149.99, 70);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (230, 'The Second Sex', 'Books', 18.25, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (231, 'Rock Climbing Harness', 'Sports & Outdoors', 65.99, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (232, 'One Hundred Years of Solitude', 'Books', 14.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (233, 'Climbing Shoes', 'Sports & Outdoors', 99.95, 100);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (234, 'Love in the Time of Cholera', 'Books', 13.80, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (235, 'Chalk Bag', 'Sports & Outdoors', 19.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (236, 'The Stranger', 'Books', 10.50, 490);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (237, 'Belay Device', 'Sports & Outdoors', 29.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (238, 'The Plague', 'Books', 11.99, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (239, 'Climbing Rope', 'Sports & Outdoors', 199.00, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (240, 'The Fall', 'Books', 9.99, 510);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (241, 'Crash Pad', 'Sports & Outdoors', 299.99, 30);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (242, 'Nausea', 'Books', 12.50, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (243, 'Bike Helmet', 'Sports & Outdoors', 59.99, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (244, 'No Exit and Three Other Plays', 'Books', 14.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (245, 'Bike Lock', 'Sports & Outdoors', 34.95, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (246, 'The Sound and the Fury', 'Books', 13.25, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (247, 'Bike Lights', 'Sports & Outdoors', 25.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (248, 'As I Lay Dying', 'Books', 11.80, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (249, 'Bike Pump', 'Sports & Outdoors', 29.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (250, 'Go Down, Moses', 'Books', 14.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (251, 'Water Bottle Cage', 'Sports & Outdoors', 12.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (252, 'The Grapes of Wrath', 'Books', 12.75, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (253, 'Bike Repair Tool Kit', 'Sports & Outdoors', 45.00, 170);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (254, 'East of Eden', 'Books', 16.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (255, 'Pannier Bag', 'Sports & Outdoors', 75.99, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (256, 'Of Mice and Men', 'Books', 9.99, 530);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (257, 'Cycling Jersey', 'Apparel', 69.95, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (258, 'The Sun Also Rises', 'Books', 11.50, 440);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (259, 'Cycling Shorts', 'Apparel', 89.99, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (260, 'A Farewell to Arms', 'Books', 12.25, 410);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (261, 'Cycling Gloves', 'Accessories', 24.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (262, 'For Whom the Bell Tolls', 'Books', 14.75, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (263, 'Fishing Rod', 'Sports & Outdoors', 89.99, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (264, 'The Old Man and the Sea', 'Books', 9.50, 550);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (265, 'Fishing Reel', 'Sports & Outdoors', 65.50, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (266, 'Slaughterhouse-Five', 'Books', 11.99, 430);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (267, 'Fishing Line', 'Sports & Outdoors', 12.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (268, 'Cat''s Cradle', 'Books', 10.99, 460);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (269, 'Tackle Box', 'Sports & Outdoors', 39.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (270, 'Breakfast of Champions', 'Books', 13.50, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (271, 'Fishing Lures Set', 'Sports & Outdoors', 29.95, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (272, 'On the Road', 'Books', 12.50, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (273, 'Waders', 'Sports & Outdoors', 129.99, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (274, 'The Dharma Bums', 'Books', 11.75, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (275, 'Fillet Knife', 'Sports & Outdoors', 24.99, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (276, 'Fear and Loathing in Las Vegas', 'Books', 13.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (277, 'Kayak', 'Sports & Outdoors', 499.00, 40);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (278, 'The Rum Diary', 'Books', 12.80, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (279, 'Paddle', 'Sports & Outdoors', 79.95, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (280, 'Infinite Jest', 'Books', 22.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (281, 'Life Vest', 'Sports & Outdoors', 49.99, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (282, 'A Supposedly Fun Thing I''ll Never Do Again', 'Books', 15.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (283, 'Dry Bag for Kayaking', 'Sports & Outdoors', 28.99, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (284, 'Consider the Lobster', 'Books', 16.25, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (285, 'Kayak Cart', 'Sports & Outdoors', 69.99, 100);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (286, 'White Teeth', 'Books', 14.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (287, 'Stand Up Paddleboard', 'Sports & Outdoors', 699.99, 35);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (288, 'On Beauty', 'Books', 13.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (289, 'SUP Paddle', 'Sports & Outdoors', 99.99, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (290, 'Swing Time', 'Books', 15.25, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (291, 'Ankle Leash for SUP', 'Sports & Outdoors', 22.50, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (292, 'Americanah', 'Books', 14.80, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (293, 'Electric Air Pump for SUP', 'Sports & Outdoors', 55.00, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (294, 'Half of a Yellow Sun', 'Books', 13.75, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (295, 'Surfboard', 'Sports & Outdoors', 599.00, 45);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (296, 'Purple Hibiscus', 'Books', 12.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (297, 'Wetsuit', 'Sports & Outdoors', 199.95, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (298, 'The Thing Around Your Neck', 'Books', 11.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (299, 'Surf Wax', 'Sports & Outdoors', 4.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (300, 'Homegoing', 'Books', 14.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (301, 'Transcendental Kingdom', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (302, 'The Underground Railroad', 'Books', 15.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (303, 'The Nickel Boys', 'Books', 13.25, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (304, 'The Water Dancer', 'Books', 17.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (305, 'Between the World and Me', 'Books', 14.75, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (306, 'The Sympathizer', 'Books', 16.00, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (307, 'The Committed', 'Books', 19.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (308, 'The Overstory', 'Books', 18.99, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (309, 'Bewilderment', 'Books', 20.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (310, 'Cloud Cuckoo Land', 'Books', 24.00, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (311, 'All the Light We Cannot See', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (312, 'Great Circle', 'Books', 22.00, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (313, 'The Lincoln Highway', 'Books', 25.00, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (314, 'A Gentleman in Moscow', 'Books', 17.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (315, 'Rules of Civility', 'Books', 14.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (316, 'Harlem Shuffle', 'Books', 21.00, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (317, 'Matrix', 'Books', 19.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (318, 'Fates and Furies', 'Books', 16.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (319, 'Crossroads', 'Books', 23.50, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (320, 'The Corrections', 'Books', 15.80, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (321, 'Freedom', 'Books', 17.25, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (322, 'Purity', 'Books', 18.75, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (323, 'Beautiful World, Where Are You', 'Books', 20.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (324, 'Normal People', 'Books', 14.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (325, 'Conversations with Friends', 'Books', 13.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (326, 'A Little Life', 'Books', 18.99, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (327, 'The People in the Trees', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (328, 'My Year of Rest and Relaxation', 'Books', 14.25, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (329, 'Eileen', 'Books', 13.50, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (330, 'Fleishman Is in Trouble', 'Books', 16.80, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (331, 'Leave the World Behind', 'Books', 19.95, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (332, 'Interior Chinatown', 'Books', 17.00, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (333, 'Deacon King Kong', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (334, 'Shuggie Bain', 'Books', 17.80, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (335, 'Hamnet', 'Books', 16.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (336, 'The Dutch House', 'Books', 17.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (337, 'Commonwealth', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (338, 'Bel Canto', 'Books', 14.75, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (339, 'This Is How You Lose the Time War', 'Books', 12.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (340, 'Gideon the Ninth', 'Books', 18.25, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (341, 'Harrow the Ninth', 'Books', 19.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (342, 'The City We Became', 'Books', 17.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (343, 'The Fifth Season', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (344, 'The Obelisk Gate', 'Books', 16.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (345, 'The Stone Sky', 'Books', 17.25, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (346, 'How Long ''til Black Future Month?', 'Books', 15.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (347, 'Binti', 'Books', 9.99, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (348, 'Lagoon', 'Books', 14.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (349, 'Ancillary Justice', 'Books', 16.80, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (350, 'The Priory of the Orange Tree', 'Books', 25.00, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (351, 'A Memory Called Empire', 'Books', 18.75, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (352, 'The Ten Thousand Doors of January', 'Books', 17.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (353, 'The Starless Sea', 'Books', 22.00, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (354, 'Mexican Gothic', 'Books', 16.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (355, 'Gods of Jade and Shadow', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (356, 'The House in the Cerulean Sea', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (357, 'Under the Whispering Door', 'Books', 20.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (358, 'Piranesi', 'Books', 19.00, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (359, 'Jonathan Strange & Mr Norrell', 'Books', 21.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (360, 'The Poppy War', 'Books', 17.80, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (361, 'The Dragon Republic', 'Books', 18.99, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (362, 'The Burning God', 'Books', 20.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (363, 'Jade City', 'Books', 17.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (364, 'Jade War', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (365, 'Jade Legacy', 'Books', 21.00, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (366, 'Black Sun', 'Books', 19.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (367, 'Fevered Star', 'Books', 22.00, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (368, 'Ninth House', 'Books', 18.25, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (369, 'Red, White & Royal Blue', 'Books', 14.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (370, 'The Song of Achilles', 'Books', 15.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (371, 'Circe', 'Books', 16.75, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (372, 'A Deadly Education', 'Books', 17.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (373, 'The Last Graduate', 'Books', 19.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (374, 'The Golden Enclaves', 'Books', 21.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (375, 'A Master of Djinn', 'Books', 18.99, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (376, 'She Who Became the Sun', 'Books', 20.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (377, 'Iron Widow', 'Books', 19.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (378, 'The Unbroken', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (379, 'The Jasmine Throne', 'Books', 20.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (380, 'A Marvellous Light', 'Books', 19.25, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (381, 'Winter''s Orbit', 'Books', 17.80, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (382, 'Light from Uncommon Stars', 'Books', 21.00, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (383, 'The Galaxy, and the Ground Within', 'Books', 18.99, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (384, 'Project Hail Mary', 'Books', 22.50, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (385, 'Klara and the Sun', 'Books', 20.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (386, 'No One Is Talking About This', 'Books', 16.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (387, 'Detransition, Baby', 'Books', 17.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (388, 'Crying in H Mart', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (389, 'The Anthropocene Reviewed', 'Books', 20.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (390, 'Empire of Pain', 'Books', 24.00, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (391, 'The Code Breaker', 'Books', 25.00, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (392, 'Four Hundred Souls', 'Books', 23.00, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (393, 'The Sum of Us', 'Books', 21.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (394, 'How the Word Is Passed', 'Books', 22.50, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (395, 'The 1619 Project: A New Origin Story', 'Books', 30.00, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (396, 'Cybernetic Ghost', 'Electronics', 1299.99, 15);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (397, 'Ethereal Weave Shawl', 'Apparel', 120.00, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (398, 'Dragonfruit Elixir', 'Groceries', 8.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (399, 'Vortex Climbing Shoes', 'Sports & Outdoors', 180.00, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (400, 'A Symphony of Stars', 'Books', 25.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (401, 'Obsidian Chef Knife', 'Home & Kitchen', 150.00, 100);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (402, 'Aura Smart Ring', 'Electronics', 299.00, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (403, 'Timeless Trench Coat', 'Apparel', 350.00, 60);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (404, 'Cryo-Sleep Chamber (Model Z)', 'Furniture', 15000.00, 5);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (405, 'Zero-G Yoga Mat', 'Sports & Outdoors', 99.99, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (406, 'Bio-Luminescent House Plant', 'Garden', 75.00, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (407, 'Sentient AI Assistant', 'Software', 999.99, 25);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (408, 'Holographic Chess Set', 'Toys & Games', 250.00, 75);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (409, 'Sonic Cleansing Brush', 'Health & Beauty', 89.50, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (410, 'Gourmet Algae Crisps', 'Groceries', 6.50, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (411, 'Steampunk Goggles', 'Accessories', 78.99, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (412, 'The Last Chronicle of Barset', 'Books', 32.00, 88);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (413, 'Hoverboard X-Wing', 'Sports & Outdoors', 899.00, 40);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (414, 'Anti-Gravity Boots', 'Apparel', 450.00, 55);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (415, 'Personal Weather Drone', 'Electronics', 320.00, 65);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (416, 'Myco-Protein Steak', 'Groceries', 12.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (417, 'Kinetic Energy Charger', 'Electronics', 65.00, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (418, 'Dream Weaver Headset', 'Health & Beauty', 199.99, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (419, 'Self-Assembling Bookshelf', 'Furniture', 450.00, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (420, 'Chronoscape: A History of the Future', 'Books', 28.50, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (421, 'Smart Fabric T-Shirt', 'Apparel', 89.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (422, 'Edible Water Orbs', 'Groceries', 3.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (423, 'Neural Interface VR System', 'Electronics', 2500.00, 20);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (424, 'Robotic Bartender', 'Home & Kitchen', 1200.00, 30);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (425, 'Photosynthetic Scarf', 'Accessories', 150.00, 95);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (426, 'The Quantum Thief', 'Books', 19.99, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (427, 'Portable Fusion Reactor (Mini)', 'Electronics', 50000.00, 2);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (428, 'Aerogel Insulated Jacket', 'Apparel', 600.00, 45);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (429, 'Glow-in-the-Dark Sushi', 'Groceries', 25.00, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (430, 'Universal Language Translator Earbud', 'Electronics', 179.99, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (431, 'Self-Healing Cutting Board', 'Home & Kitchen', 55.00, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (432, 'The Diamond Age', 'Books', 18.75, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (433, 'Sonic Screwdriver (Replica)', 'Toys & Games', 49.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (434, 'Programmable Matter Clay', 'Arts & Crafts', 99.00, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (435, 'Personalized DNA Portrait', 'Arts & Crafts', 299.00, 70);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (436, 'Cryo-Preserved Vintage Wine', 'Groceries', 500.00, 25);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (437, 'Sentient Plant Companion', 'Garden', 125.00, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (438, 'Mind-Controlled Drone', 'Toys & Games', 499.99, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (439, 'Zero-Point Energy Drink', 'Groceries', 9.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (440, 'Permutation City', 'Books', 21.00, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (441, 'Holographic Pet', 'Toys & Games', 79.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (442, 'Adaptive Camouflage Cloak', 'Apparel', 1200.00, 18);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (443, 'Smart Contact Lenses with HUD', 'Electronics', 850.00, 40);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (444, '3D Food Printer', 'Home & Kitchen', 750.00, 60);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (445, 'The Windup Girl', 'Books', 17.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (446, 'Nanobot Cleaning Solution', 'Home & Kitchen', 45.00, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (447, 'Memory Foam Sidewalk', 'Garden', 250.00, 35);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (448, 'Time-Dilating Hourglass', 'Home & Kitchen', 999.00, 10);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (449, 'Exo-Skeleton Power Suit (Lite)', 'Sports & Outdoors', 3500.00, 12);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (450, 'A Fire Upon the Deep', 'Books', 20.50, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (451, 'Graphene Bicycle Frame', 'Sports & Outdoors', 2200.00, 22);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (452, 'Self-Watering, Self-Fertilizing Planter', 'Garden', 85.99, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (453, 'Augmented Reality Board Game', 'Toys & Games', 129.95, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (454, 'Lab-Grown Diamond Necklace', 'Accessories', 1500.00, 30);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (455, 'Blindsight', 'Books', 19.50, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (456, 'Personalized Genetic Ancestry Novel', 'Books', 199.00, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (457, 'Sound-Dampening Wall Panels', 'Furniture', 320.00, 75);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (458, 'Antimatter Paperweight', 'Office Supplies', 10000.00, 3);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (459, 'Flavor-Changing Chewing Gum', 'Groceries', 5.50, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (460, 'The Dispossessed', 'Books', 16.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (461, 'Quantum Entanglement Communication Set', 'Electronics', 8000.00, 8);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (462, 'Self-Tying Shoelaces', 'Accessories', 39.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (463, 'Personal Force Field Generator (Beta)', 'Electronics', 1800.00, 15);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (464, 'Echopraxia', 'Books', 21.99, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (465, 'Mood-Sensing Wallpaper', 'Home & Kitchen', 150.00, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (466, 'Hydroponic Vertical Farm', 'Garden', 600.00, 40);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (467, 'Solar Sail Kite', 'Sports & Outdoors', 350.00, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (468, 'The Left Hand of Darkness', 'Books', 15.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (469, 'Instant Sobriety Pill', 'Health & Beauty', 29.99, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (470, 'Teleportation Pad (Short Range)', 'Electronics', 75000.00, 1);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (471, 'Hyper-Caffeinated Coffee Beans', 'Groceries', 25.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (472, 'Neuromancer', 'Books', 14.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (473, 'Bio-Printed Leather Jacket', 'Apparel', 950.00, 35);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (474, 'Gravity-Defying Bookshelf', 'Furniture', 550.00, 45);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (475, 'Emotion-Enhancing Music Player', 'Electronics', 220.00, 90);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (476, 'Snow Crash', 'Books', 17.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (477, 'Portable Wormhole Generator (Unstable)', 'Electronics', 100000.00, 1);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (478, 'Self-Replicating Pen', 'Office Supplies', 88.00, 100);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (479, 'Altered Carbon', 'Books', 18.99, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (480, 'Sentient Dust Bunnies', 'Pets', 15.00, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (481, 'Universal Constructor Nanites', 'Arts & Crafts', 5000.00, 10);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (482, 'The Three-Body Problem', 'Books', 19.99, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (483, 'Pocket Sun', 'Home & Kitchen', 120.00, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (484, 'The Dark Forest', 'Books', 20.99, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (485, 'Anti-Senescence Treatment', 'Health & Beauty', 25000.00, 5);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (486, 'Death''s End', 'Books', 22.50, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (487, 'Weather Control Orb', 'Garden', 4500.00, 7);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (488, 'A Canticle for Leibowitz', 'Books', 16.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (489, 'T-Shirt of Invisibility (Flickers)', 'Apparel', 300.00, 60);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (490, 'Starmaker', 'Books', 15.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (491, 'Lucid Dreaming Pills', 'Health & Beauty', 49.95, 170);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (492, 'The Man in the High Castle', 'Books', 14.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (493, 'Instant Treehouse Kit', 'Garden', 899.99, 30);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (494, 'Do Androids Dream of Electric Sheep?', 'Books', 13.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (495, 'Personalized Soundtrack Generator', 'Software', 29.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (496, 'Ubik', 'Books', 12.99, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (497, 'Self-Driving Briefcase', 'Accessories', 450.00, 55);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (498, 'A Scanner Darkly', 'Books', 14.50, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (499, 'Gourmet Insect Flour', 'Groceries', 18.00, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (500, 'Foundation', 'Books', 11.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (501, 'Rustic Farmhouse Dining Table', 'Furniture', 799.00, 25);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (502, 'Spiced Apple Cider Mix', 'Groceries', 9.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (503, 'The Silmarillion', 'Books', 21.99, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (504, 'Hand-Knit Wool Sweater', 'Apparel', 149.95, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (505, 'Professional Condenser Microphone', 'Electronics', 189.00, 95);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (506, 'Leather-Bound Journal', 'Office Supplies', 28.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (507, 'Gourmet Truffle Salt', 'Groceries', 15.75, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (508, 'The Name of the Wind', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (509, 'Antique World Map Print', 'Home Decor', 45.00, 120);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (510, 'Portable Power Station', 'Electronics', 399.99, 60);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (511, 'Organic Earl Grey Tea', 'Groceries', 8.50, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (512, 'The Wise Man''s Fear', 'Books', 19.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (513, 'Velvet Accent Chair', 'Furniture', 299.00, 45);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (514, 'Calligraphy Pen Set', 'Arts & Crafts', 38.99, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (515, 'Retinol Night Cream', 'Health & Beauty', 32.00, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (516, 'The Way of Kings', 'Books', 22.50, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (517, 'Smart Thermostat', 'Home & Kitchen', 199.00, 110);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (518, 'Gourmet Balsamic Vinegar', 'Groceries', 25.00, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (519, 'Words of Radiance', 'Books', 23.99, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (520, 'Linen Duvet Cover Set', 'Home Decor', 179.99, 70);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (521, 'Electric Standing Desk', 'Furniture', 499.00, 50);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (522, 'Oathbringer', 'Books', 25.00, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (523, 'Noise-Cancelling Earbuds', 'Electronics', 179.95, 140);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (524, 'Organic Maple Syrup', 'Groceries', 14.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (525, 'Rhythm of War', 'Books', 26.50, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (526, 'Weighted Hula Hoop', 'Sports & Outdoors', 29.99, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (527, 'Mistborn: The Final Empire', 'Books', 16.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (528, 'Air Purifying Plant (Snake Plant)', 'Garden', 24.95, 160);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (529, 'The Well of Ascension', 'Books', 17.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (530, 'Silk Pillowcase', 'Home Decor', 35.00, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (531, 'The Hero of Ages', 'Books', 18.25, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (532, 'Cordless Stick Vacuum', 'Home & Kitchen', 249.99, 80);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (533, 'Elantris', 'Books', 15.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (534, 'Beeswax Food Wraps', 'Home & Kitchen', 19.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (535, 'Warbreaker', 'Books', 17.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (536, 'Digital Drawing Tablet', 'Electronics', 99.99, 150);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (537, 'The Eye of the World', 'Books', 14.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (538, 'Aged Cheddar Cheese', 'Groceries', 12.50, 180);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (539, 'The Great Hunt', 'Books', 15.50, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (540, 'Electric Pressure Cooker', 'Home & Kitchen', 119.95, 130);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (541, 'The Dragon Reborn', 'Books', 15.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (542, 'Gardening Gloves with Claws', 'Garden', 15.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (543, 'The Shadow Rising', 'Books', 16.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (544, 'Satin Pajama Set', 'Apparel', 59.99, 170);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (545, 'The Fires of Heaven', 'Books', 16.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (546, 'A Game of Thrones', 'Books', 13.99, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (547, 'A Clash of Kings', 'Books', 14.50, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (548, 'A Storm of Swords', 'Books', 15.99, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (549, 'A Feast for Crows', 'Books', 16.25, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (550, 'A Dance with Dragons', 'Books', 17.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (551, 'The Lies of Locke Lamora', 'Books', 16.80, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (552, 'Red Seas Under Red Skies', 'Books', 17.25, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (553, 'The Republic of Thieves', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (554, 'The Blade Itself', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (555, 'Before They Are Hanged', 'Books', 16.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (556, 'Last Argument of Kings', 'Books', 17.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (557, 'Best Served Cold', 'Books', 18.25, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (558, 'The Heroes', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (559, 'Red Country', 'Books', 18.75, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (560, 'A Little Hatred', 'Books', 20.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (561, 'The Trouble with Peace', 'Books', 21.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (562, 'The Wisdom of Crowds', 'Books', 22.99, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (563, 'Gardens of the Moon', 'Books', 17.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (564, 'Deadhouse Gates', 'Books', 18.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (565, 'Memories of Ice', 'Books', 19.25, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (566, 'House of Chains', 'Books', 19.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (567, 'Midnight Tides', 'Books', 20.50, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (568, 'The Bonehunters', 'Books', 21.00, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (569, 'Reaper''s Gale', 'Books', 21.50, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (570, 'Toll the Hounds', 'Books', 22.00, 210);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (571, 'Dust of Dreams', 'Books', 22.50, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (572, 'The Crippled God', 'Books', 23.00, 190);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (573, 'The Black Company', 'Books', 14.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (574, 'Shadows Linger', 'Books', 15.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (575, 'The White Rose', 'Books', 15.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (576, 'The Fifth Elephant', 'Books', 13.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (577, 'Night Watch', 'Books', 14.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (578, 'Going Postal', 'Books', 14.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (579, 'Thud!', 'Books', 15.25, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (580, 'Making Money', 'Books', 15.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (581, 'Unseen Academicals', 'Books', 15.75, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (582, 'I Shall Wear Midnight', 'Books', 16.00, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (583, 'Snuff', 'Books', 16.25, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (584, 'Raising Steam', 'Books', 16.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (585, 'The Shepherd''s Crown', 'Books', 16.75, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (586, 'Good Omens', 'Books', 13.50, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (587, 'American Gods', 'Books', 14.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (588, 'Anansi Boys', 'Books', 14.25, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (589, 'The Ocean at the End of the Lane', 'Books', 12.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (590, 'Norse Mythology', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (591, 'Stardust', 'Books', 11.99, 410);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (592, 'Neverwhere', 'Books', 13.25, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (593, 'The Graveyard Book', 'Books', 12.50, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (594, 'Coraline', 'Books', 10.99, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (595, 'The Sandman, Vol. 1: Preludes & Nocturnes', 'Books', 19.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (596, 'The Sandman, Vol. 2: The Doll''s House', 'Books', 20.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (597, 'The Sandman, Vol. 3: Dream Country', 'Books', 21.00, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (598, 'The Sandman, Vol. 4: Season of Mists', 'Books', 21.50, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (599, 'The Sandman, Vol. 5: A Game of You', 'Books', 22.00, 240);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (600, 'The Sandman, Vol. 6: Fables & Reflections', 'Books', 22.50, 230);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (601, 'Solaris', 'Books', 14.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (602, 'The Cyberiad', 'Books', 15.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (603, 'Fiasco', 'Books', 16.25, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (604, 'His Master''s Voice', 'Books', 15.99, 295);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (605, 'Roadside Picnic', 'Books', 13.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (606, 'Hard to Be a God', 'Books', 14.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (607, 'We', 'Books', 12.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (608, 'The Master and Margarita', 'Books', 14.75, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (609, 'Heart of a Dog', 'Books', 11.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (610, 'Notes from Underground', 'Books', 9.99, 450);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (611, 'The Idiot', 'Books', 15.25, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (612, 'Demons', 'Books', 16.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (613, 'The Death of Ivan Ilyich', 'Books', 8.99, 500);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (614, 'Hadji Murat', 'Books', 10.50, 420);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (615, 'Fathers and Sons', 'Books', 11.75, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (616, 'A Hero of Our Time', 'Books', 12.25, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (617, 'Dead Souls', 'Books', 13.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (618, 'The Overcoat', 'Books', 7.99, 550);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (619, 'The Queen of Spades', 'Books', 9.50, 480);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (620, 'Eugene Onegin', 'Books', 13.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (621, 'If on a winter''s night a traveler', 'Books', 15.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (622, 'Invisible Cities', 'Books', 14.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (623, 'The Baron in the Trees', 'Books', 13.80, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (624, 'The Cloven Viscount', 'Books', 12.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (625, 'The Nonexistent Knight', 'Books', 12.50, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (626, 'Cosmicomics', 'Books', 14.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (627, 'The Name of the Rose', 'Books', 16.75, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (628, 'Foucault''s Pendulum', 'Books', 18.50, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (629, 'The Island of the Day Before', 'Books', 17.25, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (630, 'Baudolino', 'Books', 19.99, 250);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (631, 'The Prague Cemetery', 'Books', 18.99, 260);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (632, 'Labyrinths', 'Books', 15.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (633, 'Ficciones', 'Books', 14.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (634, 'The Aleph and Other Stories', 'Books', 14.25, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (635, 'The Book of Sand', 'Books', 13.50, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (636, 'Hopscotch', 'Books', 17.80, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (637, 'Blow-Up and Other Stories', 'Books', 14.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (638, 'The Savage Detectives', 'Books', 18.25, 270);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (639, '2666', 'Books', 25.00, 200);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (640, 'By Night in Chile', 'Books', 13.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (641, 'The House of the Spirits', 'Books', 15.99, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (642, 'Eva Luna', 'Books', 14.50, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (643, 'Paula', 'Books', 13.75, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (644, 'The Motorcycle Diaries', 'Books', 12.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (645, 'The Open Veins of Latin America', 'Books', 16.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (646, 'The Book of Embraces', 'Books', 14.80, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (647, 'The Alchemist', 'Books', 13.50, 400);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (648, 'Veronika Decides to Die', 'Books', 12.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (649, 'Eleven Minutes', 'Books', 13.25, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (650, 'The Zahir', 'Books', 14.00, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (651, 'Like Water for Chocolate', 'Books', 12.80, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (652, 'The Law of Love', 'Books', 13.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (653, 'Blindness', 'Books', 15.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (654, 'The Cave', 'Books', 16.25, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (655, 'The Double', 'Books', 14.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (656, 'All the Names', 'Books', 15.80, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (657, 'The Wind-Up Bird Chronicle', 'Books', 17.99, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (658, 'Kafka on the Shore', 'Books', 16.99, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (659, '1Q84', 'Books', 24.00, 220);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (660, 'Norwegian Wood', 'Books', 14.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (661, 'Sputnik Sweetheart', 'Books', 13.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (662, 'After Dark', 'Books', 13.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (663, 'The Elephant Vanishes', 'Books', 14.25, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (664, 'Kitchen', 'Books', 12.99, 370);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (665, 'Goodbye, Tsugumi', 'Books', 11.99, 390);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (666, 'The Housekeeper and the Professor', 'Books', 13.80, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (667, 'The Diving Pool', 'Books', 12.50, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (668, 'The Sailor Who Fell from Grace with the Sea', 'Books', 13.25, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (669, 'The Temple of the Golden Pavilion', 'Books', 14.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (670, 'Confessions of a Mask', 'Books', 14.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (671, 'Spring Snow', 'Books', 15.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (672, 'Snow Country', 'Books', 13.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (673, 'Thousand Cranes', 'Books', 13.50, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (674, 'The Sound of the Mountain', 'Books', 14.25, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (675, 'The Old Capital', 'Books', 14.80, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (676, 'The Woman in the Dunes', 'Books', 15.25, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (677, 'The Face of Another', 'Books', 14.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (678, 'The Ruined Map', 'Books', 15.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (679, 'The Box Man', 'Books', 14.75, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (680, 'Out', 'Books', 16.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (681, 'Grotesque', 'Books', 15.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (682, 'The Vegetarian', 'Books', 14.99, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (683, 'Human Acts', 'Books', 16.25, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (684, 'The White Book', 'Books', 17.50, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (685, 'Please Look After Mom', 'Books', 13.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (686, 'The Girl Who Wrote Loneliness', 'Books', 14.50, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (687, 'The Hen Who Dreamed She Could Fly', 'Books', 12.99, 380);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (688, 'Pachinko', 'Books', 17.80, 290);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (689, 'Free Food for Millionaires', 'Books', 16.50, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (690, 'The Namesake', 'Books', 14.99, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (691, 'Interpreter of Maladies', 'Books', 13.99, 360);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (692, 'The Lowland', 'Books', 15.50, 330);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (693, 'Unaccustomed Earth', 'Books', 14.80, 340);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (694, 'The God of Small Things', 'Books', 14.99, 350);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (695, 'The Ministry of Utmost Happiness', 'Books', 17.25, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (696, 'A Fine Balance', 'Books', 18.50, 280);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (697, 'Such a Long Journey', 'Books', 15.99, 320);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (698, 'Midnight''s Children', 'Books', 16.99, 310);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (699, 'The Satanic Verses', 'Books', 17.50, 300);
INSERT INTO Product (ProductID, ProductName, Category, Price, StockQuantity) VALUES (700, 'Shame', 'Books', 15.25, 330);
